之前那个请关闭，修改了一些错误地方
friendlyhj/Zentutorial pull request #2
Opened 2020-08-25 14:29 UTC by XHL315

2020-08-25 14:30 UTC, XHL315 commented
我的魔改还是有点烂，所以写的可能会有点错误，本人也是第一次写这种教程，不是很会写，见谅

2020-08-25 14:31 UTC, friendlyhj commented
你先写，写好了再说（

2020-08-25 14:32 UTC, XHL315 commented
给您看一眼

2020-08-25 14:32 UTC, XHL315 commented
写的怎么样？

2020-08-25 14:33 UTC, friendlyhj commented
尽量不要重命名文件，如果需要新添页的话，你需要修改 SUMMARY.md

2020-08-25 14:33 UTC, XHL315 commented
第一次用GitHub（

2020-08-25 14:34 UTC, XHL315 commented
所以很多都不懂

2020-08-26 04:53 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/README.md
> +## 匠魂联动部分不是youyihj大佬本人做的,所以内容可能会有点奇怪(?)~~(也会有写的不好的地方,我的魔改也不是好好,本人英语也是菜鸡,所以有些地方可能会有些问题,见谅)~~
写上自己的名字。还有这个也算是正式文档了，最好用一些正式点的语言。最好不要有那种不确定的表述。

2020-08-26 10:39 UTC, friendlyhj requested changes

2020-08-26 10:39 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/material.md
> +通过`import mods.contenttweaker.tconstruct.MaterialBuilder;`导入MaterialBuilder对象
导入是导包，而不是对象。
是 class，而不是 instance

2020-08-26 10:39 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/material.md
> +最后不要忘了`.register();`一下,否则会报错
确定是报错，而不是游戏内没反应吗？如果的确是报错，请标记 resolve

2020-08-26 10:39 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/trait.md
> +通过`import mods.contenttweaker.tconstruct.TraitDataRepresentation;`导入TraitDataRepresentation对象
同理

2020-08-26 10:39 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/trait.md
> +## TraitDataRepresentation
这里最好是另开一页。

2020-08-26 10:39 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/trait.md
> +最后不要忘了`.register();`一下,否则会报错
同上

2020-08-26 10:40 UTC, XHL315 commented on contenttweaker/tinkers-construct-addon/trait.md
> +最后不要忘了`.register();`一下,否则会报错
噢，我的问题挺多

2020-08-26 10:41 UTC, XHL315 commented on contenttweaker/tinkers-construct-addon/trait.md
> +## TraitDataRepresentation
是从这里一直往后还是？

2020-08-26 10:41 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/material.md
> +最后不要忘了`.register();`一下,否则会报错
对了，最好用专业点的说法：调用 `register` 方法。

2020-08-26 10:43 UTC, friendlyhj commented on contenttweaker/tinkers-construct-addon/trait.md
> +## TraitDataRepresentation
最好是每一个类都有自己的一页。这样条理好点。

2020-08-26 10:43 UTC, XHL315 commented
噢，懂了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "youyihj"<notifications@github.com&gt;; 
发送时间: 2020年8月26日(星期三) 晚上6:43
收件人: "friendlyhj/Zentutorial"<Zentutorial@noreply.github.com&gt;; 
抄送: "小哈罗-121125"<3181063382@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [friendlyhj/Zentutorial] 之前那个请关闭，修改了一些错误地方 (#2)





 
@friendlyhj commented on this pull request.
 
 
In contenttweaker/tinkers-construct-addon/trait.md:
 &gt; +例子: +```javascript +myTrait.extraInfo = function(TraitRepresentation thisTrait, IItemStack item, IData tag){ +    val infos as string[] = ["1","2"]; +    for i, info in infos { +        return "Cool" ~ info; +    } +}; +``` +结果:**额外信息显示Cool1,Cool2**   + +## 访问特性数据 +例子:`val myTraitData = myTrait.getData(itemWithTrait);`   +**myTrait指特性,itemWithTrait指带有特性的工具**   + +## TraitDataRepresentation  
最好是每一个类都有自己的一页。这样条理好点。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-26 11:49 UTC, friendlyhj approved these changes

2020-08-26 11:50 UTC, merged